version: "3.8"

services:
  achat_backend:
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
    image: ahmedbelhaj2/achat_backend:1.0.0
    container_name: achatback321
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


  mysql-db:
    image: mysql:5.7
    container_name: achat_mysql292
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql



volumes:
  db_data:
