version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  achat:
    depends_on:
      - mysqldb
    image: ahmedbelhaj2/achat_backend:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
       spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb,
       spring.datasource.username=ahmed,
       spring.datasource.password=1234,
       spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect,
      
      }'
    stdin_open: true
    tty: true

volumes:
  db :
