version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  achat_backend:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    image: ahmedbelhaj2/achat_backend:1.0.0
    restart: on-failure
    ports:
      - '8089:8089'
    stdin_open: true
    tty: true

volumes:
  db :
